# https://github.com/typst/packages

[package]
name = "copropriete-avis"
version = "1.1.0"
entrypoint = "src/lib.typ"
authors = [ "Léo Colombaro <@LeoColomb>" ]
license = "MIT"
description = ""
repository = "https://github.com/LeoColomb/dotdocs"
keywords = [
  "copropriété",
]
categories = [ ]
disciplines = [ ]
exclude = [
  "tests",
]
# renovate: image=ghcr.io/typst/typst
compiler = "0.15.1"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.svg"
