# https://github.com/typst/packages

[package]
name = "logotype"
version = "1.0.0"
entrypoint = "src/lib.typ"
authors = ["Léo Colombaro <@LeoColomb>"]
license = "MIT"
description = ""
repository = "https://github.com/LeoColomb/dotdocs"
keywords = []
categories = []
disciplines = []
compiler = ""
