#!/usr/bin/env bash
set -eu
shopt -s globstar

# adapted from https://github.com/johannes-wolf/cetz/blob/35c0868378cea5ad323cc0d9c2f76de8ed9ba5bd/scripts/package
# licensed under Apache License 2.0

. "$(dirname "${BASH_SOURCE[0]}")/setup"

if (( $# < 1 )) || [[ "${1:-}" == "help" ]]; then
  echo "package TARGET"
  echo ""
  echo "Packages all relevant files into a directory named '<name>/<version>'"
  echo "at TARGET. If TARGET is set to @local or @preview, the local Typst package"
  echo "directory will be used so that the package gets installed for local use."
  echo "The name and version are read from 'typst.toml' in the project root."
  echo ""
  echo "Local package prefix: $DATA_DIR/typst/package/local"
  echo "Local preview package prefix: $DATA_DIR/typst/package/preview"
  exit 1
fi

TARGET="$(resolve-target "${1:?Missing target path, @local or @preview}")"
echo "Install dir: $TARGET"

for root in packages/*/ ; do
  echo "Install package: ${root}"

  # ignore rules
  readarray -t ignores < <(grep -v '^#' "${root}.typstignore" | grep '[^[:blank:]]')

  # List of all files that get packaged
  readarray -t files < <(enumerate "${root}" "${root}")
  # declare -p files >&2

  TMP="$(mktemp -d)"
  PKG_PREFIX="$(read-toml "${root}typst.toml" "name")"
  VERSION="$(read-toml "${root}typst.toml" "version")"

  for f in "${files[@]}"; do
    mkdir -p "$TMP/$(dirname "$f")" 2>/dev/null
    cp -r "${root}$f" "$TMP/$f"
  done

  TARGET_PACKAGE="${TARGET:?}/${PKG_PREFIX:?}/${VERSION:?}"
  echo "Packaged to: $TARGET_PACKAGE"
  if rm -r "${TARGET_PACKAGE:?}" 2>/dev/null; then
    echo "Overwriting existing version."
  fi
  mkdir -p "$TARGET_PACKAGE"

  # include hidden files by setting dotglob
  shopt -s dotglob
  mv "$TMP"/* "$TARGET_PACKAGE"
done
