#!/usr/bin/env bash
# source this script to prepare some common environment variables

# adapted from https://github.com/johannes-wolf/cetz/blob/35c0868378cea5ad323cc0d9c2f76de8ed9ba5bd/scripts/package
# licensed under Apache License 2.0

# Local package directories per platform
if [[ "$OSTYPE" == "linux"* ]]; then
  DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  DATA_DIR="$HOME/Library/Application Support"
else
  DATA_DIR="${APPDATA}"
fi

function read-toml() {
  local file="$1"
  local key="$2"
  # Read a key value pair in the format: <key> = "<value>"
  # stripping surrounding quotes.
  perl -lne "print \"\$1\" if /^${key}\\s*=\\s*\"(.*)\"/" < "$file"
}

function resolve-target() {
  local target="$1"

  if [[ "$target" == "@local" ]]; then
    echo "${DATA_DIR}/typst/packages/local"
  elif [[ "$target" == "@preview" ]]; then
    echo "${DATA_DIR}/typst/packages/preview"
  else
    echo "$target"
  fi
}

# recursively print all files that are not excluded via .typstignore
function enumerate {
  local current="$1"
  local root="$2"
  if [[ -f "$current" ]]; then
    echo ${current#"$root"}
  else
    local files
    readarray -t files < <(find "$current" \
      -mindepth 1 -maxdepth 1 \
      -not -name .git \
      -not -name .typstignore)
    # declare -p files >&2

    local f
    for f in "${files[@]}"; do
      local include
      include=1

      local ignore
      for ignore in "${ignores[@]}"; do
        if [[ "$ignore" =~ ^! ]]; then
          ignore="${ignore:1}"
          if [[ "$f" == ./$ignore ]]; then
            # echo "\"$f\" matched \"!$ignore\"" >&2
            include=1
          fi
        elif [[ "$f" == ./$ignore ]]; then
          # echo "\"$f\" matched \"$ignore\"" >&2
          include=0
        fi
      done
      if [[ "$include" == 1 ]]; then
        enumerate "$f" "$root"
      fi
    done
  fi
}
